id: I4D699D7A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:58:36+00:00'
last_modified: '2022-06-08T06:25:59.973832+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG20785
  title: ངག་རྩོམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    052E:
      image_group_id: I1KG20883
      title: ''
      total_pages: 538
      order: 1
      base_file: 052E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
