id: P006727
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:19:33.856157
source_metadata:
  id: bdr:W1KG20785
  title: ངག་རྩོམ།
  author: ''
  volumes:
    eff61f73aa254d989479033a5526005d:
      image_group_id: I1KG20883
      title: ''
      volume_number: 1
      total_pages: 538
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
